CREATE TABLE faculty (
                         faculty_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         faculty_name VARCHAR(150) NOT NULL UNIQUE,
                         dean_name VARCHAR(150) NOT NULL,
                         office_email VARCHAR(150) UNIQUE
);

CREATE TABLE department (
                            department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            faculty_id BIGINT NOT NULL REFERENCES faculty(faculty_id)
                                ON UPDATE CASCADE
                                ON DELETE RESTRICT,
                            department_name VARCHAR(150) NOT NULL,
                            office_phone VARCHAR(30),
                            CONSTRAINT uq_department_name_per_faculty UNIQUE (faculty_id, department_name)
);

CREATE TABLE teacher (
                         teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         department_id BIGINT NOT NULL REFERENCES department(department_id)
                             ON UPDATE CASCADE
                             ON DELETE RESTRICT,
                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,
                         email VARCHAR(150) NOT NULL UNIQUE,
                         academic_title VARCHAR(100) NOT NULL,
                         birth_date DATE NOT NULL,
                         hire_date DATE NOT NULL
);

CREATE TABLE student_group (
                               group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               department_id BIGINT NOT NULL REFERENCES department(department_id)
                                   ON UPDATE CASCADE
                                   ON DELETE RESTRICT,
                               group_code VARCHAR(50) NOT NULL UNIQUE,
                               start_year INTEGER NOT NULL,
                               monitor_student_id BIGINT
);

CREATE TABLE student (
                         student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         group_id BIGINT NOT NULL REFERENCES student_group(group_id)
                             ON UPDATE CASCADE
                             ON DELETE RESTRICT,
                         first_name VARCHAR(100) NOT NULL,
                         last_name VARCHAR(100) NOT NULL,
                         email VARCHAR(150) NOT NULL UNIQUE,
                         admission_year INTEGER NOT NULL,
                         CONSTRAINT uq_student_id_group UNIQUE (student_id, group_id)
);

CREATE TABLE course (
                        course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        department_id BIGINT NOT NULL REFERENCES department(department_id)
                            ON UPDATE CASCADE
                            ON DELETE RESTRICT,
                        teacher_id BIGINT NOT NULL REFERENCES teacher(teacher_id)
                            ON UPDATE CASCADE
                            ON DELETE RESTRICT,
                        group_id BIGINT NOT NULL REFERENCES student_group(group_id)
                            ON UPDATE CASCADE
                            ON DELETE RESTRICT,
                        course_code VARCHAR(30) NOT NULL UNIQUE,
                        course_name VARCHAR(150) NOT NULL,
                        credits NUMERIC(3,1) NOT NULL,
                        semester SMALLINT NOT NULL
);

CREATE TABLE enrollment (
                            enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            student_id BIGINT NOT NULL REFERENCES student(student_id)
                                ON UPDATE CASCADE
                                ON DELETE CASCADE,
                            course_id BIGINT NOT NULL REFERENCES course(course_id)
                                ON UPDATE CASCADE
                                ON DELETE CASCADE,
                            grade NUMERIC(5,2),
                            enrolled_at DATE NOT NULL DEFAULT CURRENT_DATE,
                            CONSTRAINT uq_student_course UNIQUE (student_id, course_id)
);
